# Workflow name
name: Post welcome comment
on:
# Trigger event
  pull_request:
    types: [opened]
permissions:
# Assign permissions to workflow runner
  pull-requests: write
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
